-- ============================================================================
-- Neovim Icons
-- ============================================================================

return {
	kind = {
		Codeium = "",
		Copilot = "",
		TabNine = "󰏚",

		Class = "󰠱",
		Color = "󰏘",
		Constant = "󰏿",
		Constructor = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "",
		File = "󰈙",
		Folder = "󰉋",
		FolderOpened = "",
		FolderEmpty = "",
		Function = "󰊕",
		Interface = "",
		Keyword = "󰌋",
		Method = "",
		Module = "󰆧",
		Operator = "󰆕",
		Property = "󰜢",
		Reference = "",
		Snippet = "",
		Text = "",
		TypeParameter = "󰗴",
		Unit = "",
		Value = "󰎠",

		Array = "",
		Boolean = "",
		Collapsed = "",
		Control = "",
		Key = "󰌋",
		Namespace = "󰦮",
		Null = "",
		Number = "󰎠",
		Object = "",
		Package = "",
		String = "",
		Struct = "󰆼",
		Variable = "󰀫",
	},
	git = {
		LineAdded = "",
		LineModified = "",
		LineRemoved = "",
		LineLeft = "▎",
		LineMiddle = "│",

		FileAdded = "✚",
		FileModified = "",
		FileDeleted = "",
		FileRenamed = "➜",

		Untracked = "",
		Ignored = "",
		Unstaged = "",
		Staged = "",
		Conflict = "",
	},
	ui = {
		Search = "",
		Selected = "❯",
		Pointer = "➜",
		Bug = "",
		Circle = "",
		Round = "",
		Ellipsis = "",
		Plus = "",
		Robot = "󰚩",
		LSP = "",
		Fold = "",
		ThinSpace = " ",
	},
	task = {
		Canceled = " ",
		Failure = " ",
		Success = " ",
		Running = " ",
	},
	diagnostics = {
		Error = " ",
		Warning = " ",
		Info = " ",
		Hint = " ",
	},
	spinner = { "", "", "", "", "", "", "", "", "", "", "", "", "" },
	dap = {
		Stopped = { " ", "DiagnosticWarn", "DapStoppedLine" },
		Breakpoint = " ",
		BreakpointCondition = " ",
		BreakpointRejected = { " ", "DiagnosticError" },
		LogPoint = "󰮔 ",
	},
}
